### ISSUE TITLE
Solution folders appear to cause build failure

### ISSUE THREAD

**Issue by dvdsgl** [bitrise-steplib/steps-xamarin-builder#4]
My iOS and Android app targets live in a solution folder called "Targets":

<img width="347" alt="screenshot 2015-12-02 16 50 50" src="https://cloud.githubusercontent.com/assets/108197/11548787/dacc7cc4-9914-11e5-9ef3-0e4d8cef945b.png">

Which causes the build to fail:

```
Cloning into '/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise558472508/step_src'...
+------------------------------------------------------------------------------+
| (6) Build                                                                    |
+------------------------------------------------------------------------------+
| id: https://github.com/bitrise-io/steps-xamarin-builder.git                  |
| version: master                                                              |
| collection: git                                                              |
| time: 2015-12-03T00:49:02Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
/private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise558472508/step_src/solution_analyzer/solution_analyzer.rb:4:in `readlines': No such file or directory @ rb_sysopen - ./Targets (Errno::ENOENT)
    from /private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise558472508/step_src/solution_analyzer/solution_analyzer.rb:4:in `get_xamarin_api'
    from /private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise558472508/step_src/solution_analyzer/solution_analyzer.rb:43:in `block in analyze_solution'
    from /private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise558472508/step_src/solution_analyzer/solution_analyzer.rb:29:in `each'
    from /private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise558472508/step_src/solution_analyzer/solution_analyzer.rb:29:in `analyze_solution'
    from /var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise558472508/step_src/step.rb:90:in `<main>'
========== Configs ==========
 * project: EmployeeDirectory.sln
 * configuration: Release
 * platform: iPhone
 * clean_build: false
 * command: archive
==> Archive solution: EmployeeDirectory.sln
ERRO[00:49:05] Step (Build) failed, error: (exit status 1)  
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | Build (exit code: 1)                                         | 3.6 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/gkiki90/steps-xamarin-builder/issues       |
| Source: https://github.com/gkiki90/steps-xamarin-builder                     |
+----+--------------------------------------------------------------+----------+
```

**Comment by Julien-Pires** [comment]
I have the same problem with my solution. I usually save my projects inside multiple solution directory.

```
/private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise299825057/step_src/solution_analyzer/solution_analyzer.rb:5:in `readlines': Is a directory @ io_fillbuf - fd:8 ./UITests (Errno::EISDIR)
    from /private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise299825057/step_src/solution_analyzer/solution_analyzer.rb:5:in `get_xamarin_api'
    from /private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise299825057/step_src/solution_analyzer/solution_analyzer.rb:45:in `block in analyze_solution'
    from /private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise299825057/step_src/solution_analyzer/solution_analyzer.rb:31:in `each'
    from /private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise299825057/step_src/solution_analyzer/solution_analyzer.rb:31:in `analyze_solution'
    from /var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise299825057/step_src/step.rb:90:in `<main>'
========== Configs ==========
 * project: Brawl.sln
 * configuration: Debug
 * platform: Any CPU
 * clean_build: true
 * command: archive
==> Archive solution: Brawl.sln
ERRO[10:02:25] Step (xamarin-builder@0.9.0) failed, error: (exit status 1) 
```

**Comment by birmacher** [comment]
Thanks for the issue!

We've just rolled out a new version ( 0.9.1 ). Can you please update it on your workflow editor on Bitrise and check if it has solved the issue?

Thanks!
