### ISSUE TITLE
Solution build failure on .nuget directory

### ISSUE THREAD

**Issue by lakario** [bitrise-steplib/steps-xamarin-builder#5]
The solution builder seems to be getting caught up when it scans my .nuget directory.

```
/private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise557528603/step_src/solution_analyzer/solution_analyzer.rb:5:in `readlines': Is a directory @ io_fillbuf - fd:8 src/MobileApp/.nuget (Errno::EISDIR)
    from /private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise557528603/step_src/solution_analyzer/solution_analyzer.rb:5:in `get_xamarin_api'
    from /private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise557528603/step_src/solution_analyzer/solution_analyzer.rb:45:in `block in analyze_solution'
    from /private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise557528603/step_src/solution_analyzer/solution_analyzer.rb:31:in `each'
    from /private/var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise557528603/step_src/solution_analyzer/solution_analyzer.rb:31:in `analyze_solution'
    from /var/folders/3q/xssq9x0s01z5pt03r3f4sy2c0000gn/T/bitrise557528603/step_src/step.rb:90:in `<main>'
```

This is resulting in a build failure.

**Comment by birmacher** [comment]
Thanks for the issue!

Seems to be the same as #4. I'll close it and continue the thread there.
We'll update a fix soon.

**Comment by lakario** [comment]
Whoops. Thanks @birmacher !

**Comment by birmacher** [comment]
We've just rolled out a new version ( 0.9.1 ). Can you please update it on your workflow editor on Bitrise and check if it has solved the issue?

Thanks!
